You are using a model of type llava to instantiate a model of type llava_llama. This is not supported for all configurations of models and can yield errors.
Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]Loading checkpoint shards:  33%|███▎      | 1/3 [00:06<00:12,  6.00s/it]Loading checkpoint shards:  67%|██████▋   | 2/3 [00:06<00:02,  2.76s/it]Loading checkpoint shards: 100%|██████████| 3/3 [00:06<00:00,  1.57s/it]Loading checkpoint shards: 100%|██████████| 3/3 [00:06<00:00,  2.22s/it]
WARNING:accelerate.big_modeling:Some parameters are on the meta device because they were offloaded to the cpu.
  0%|          | 0/1061 [00:00<?, ?it/s]  0%|          | 1/1061 [13:05<231:25:31, 785.97s/it]  0%|          | 1/1061 [13:55<245:52:20, 835.04s/it]
Traceback (most recent call last):
  File "/home/amulyam/miniconda3/envs/llava/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/amulyam/miniconda3/envs/llava/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/amulyam/Projects/LLaVA/llava/eval/model_vqa_science.py", line 113, in <module>
    eval_model(args)
  File "/home/amulyam/Projects/LLaVA/llava/eval/model_vqa_science.py", line 76, in eval_model
    output_ids = model.generate(
  File "/home/amulyam/miniconda3/envs/llava/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/amulyam/Projects/LLaVA/llava/model/language_model/llava_llama.py", line 137, in generate
    return super().generate(
  File "/home/amulyam/miniconda3/envs/llava/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/amulyam/miniconda3/envs/llava/lib/python3.10/site-packages/transformers/generation/utils.py", line 2215, in generate
    result = self._sample(
  File "/home/amulyam/miniconda3/envs/llava/lib/python3.10/site-packages/transformers/generation/utils.py", line 3206, in _sample
    outputs = self(**model_inputs, return_dict=True)
  File "/home/amulyam/miniconda3/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/amulyam/miniconda3/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/amulyam/miniconda3/envs/llava/lib/python3.10/site-packages/accelerate/hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/amulyam/Projects/LLaVA/llava/model/language_model/llava_llama.py", line 91, in forward
    return super().forward(
  File "/home/amulyam/miniconda3/envs/llava/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 1210, in forward
    logits = self.lm_head(hidden_states[:, -num_logits_to_keep:, :])
  File "/home/amulyam/miniconda3/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/amulyam/miniconda3/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/amulyam/miniconda3/envs/llava/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    args, kwargs = module._hf_hook.pre_forward(module, *args, **kwargs)
  File "/home/amulyam/miniconda3/envs/llava/lib/python3.10/site-packages/accelerate/hooks.py", line 355, in pre_forward
    set_module_tensor_to_device(
  File "/home/amulyam/miniconda3/envs/llava/lib/python3.10/site-packages/accelerate/utils/modeling.py", line 329, in set_module_tensor_to_device
    new_value = value.to(device)
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 314.00 MiB. GPU 0 has a total capacity of 11.90 GiB of which 125.62 MiB is free. Including non-PyTorch memory, this process has 11.78 GiB memory in use. Of the allocated memory 11.27 GiB is allocated by PyTorch, and 350.87 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
